# Generated by Django 5.0.6 on 2026-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_phone_verified_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
