# Generated by Django 5.0.6 on 2026-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='silent_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sos_type',
            field=models.CharField(choices=[('Police', 'Police'), ('Ambulance', 'Ambulance'), ('Both', 'Both')], default='Both', max_length=20),
        ),
    ]
